package li.cil.oc;

public class Constants {
    public class BlockName {
        public static final String
                Adapter = "adapter",
                Assembler = "assembler",
                Cable = "cable",
                Capacitor = "capacitor",
                CarpetedCapacitor = "carpetedcapacitor",
                CaseCreative = "casecreative",
                CaseTier1 = "case1",
                CaseTier2 = "case2",
                CaseTier3 = "case3",
                ChameliumBlock = "chameliumblock",
                Charger = "charger",
                Disassembler = "disassembler",
                DiskDrive = "diskdrive",
                Endstone = "endstone",
                Geolyzer = "geolyzer",
                HologramTier1 = "hologram1",
                HologramTier2 = "hologram2",
                Keyboard = "keyboard",
                Microcontroller = "microcontroller",
                MotionSensor = "motionsensor",
                NetSplitter = "netsplitter",
                PowerConverter = "powerconverter",
                PowerDistributor = "powerdistributor",
                Print = "print",
                Printer = "printer",
                Raid = "raid",
                Redstone = "redstone",
                Relay = "relay",
                Robot = "robot",
                RobotAfterimage = "robotafterimage",
                ScreenTier1 = "screen1",
                ScreenTier2 = "screen2",
                ScreenTier3 = "screen3",
                Rack = "rack",
                Transposer = "transposer",
                Waypoint = "waypoint";

        // def Case(tier: Int): String = ItemUtils.caseNameWithTierSuffix("case", tier)
    }

    public class ItemName {
        public static final String
                AbstractBusCard = "abstractbuscard",
                Acid = "acid",
                Alu = "alu",
                Analyzer = "analyzer",
                AngelUpgrade = "angelupgrade",
                APUCreative = "apucreative",
                APUTier1 = "apu1",
                APUTier2 = "apu2",
                ArrowKeys = "arrowkeys",
                BatteryUpgradeTier1 = "batteryupgrade1",
                BatteryUpgradeTier2 = "batteryupgrade2",
                BatteryUpgradeTier3 = "batteryupgrade3",
                ButtonGroup = "buttongroup",
                Card = "card",
                CardContainerTier1 = "cardcontainer1",
                CardContainerTier2 = "cardcontainer2",
                CardContainerTier3 = "cardcontainer3",
                Chamelium = "chamelium",
                ChipTier1 = "chip1",
                ChipTier2 = "chip2",
                ChipTier3 = "chip3",
                ChunkloaderUpgrade = "chunkloaderupgrade",
                CircuitBoard = "circuitboard",
                ComponentBusTier1 = "componentbus1",
                ComponentBusTier2 = "componentbus2",
                ComponentBusTier3 = "componentbus3",
                ComponentBusCreative = "componentbuscreative",
                CPUTier1 = "cpu1",
                CPUTier2 = "cpu2",
                CPUTier3 = "cpu3",
                CraftingUpgrade = "craftingupgrade",
                ControlUnit = "cu",
                CuttingWire = "cuttingwire",
                DatabaseUpgradeTier1 = "databaseupgrade1",
                DatabaseUpgradeTier2 = "databaseupgrade2",
                DatabaseUpgradeTier3 = "databaseupgrade3",
                DataCardTier1 = "datacard1",
                DataCardTier2 = "datacard2",
                DataCardTier3 = "datacard3",
                DebugCard = "debugcard",
                Debugger = "debugger",
                DiamondChip = "chipdiamond",
                Disk = "disk",
                DiskDriveMountable = "diskdrivemountable",
                Drone = "drone",
                DroneCaseCreative = "dronecasecreative",
                DroneCaseTier1 = "dronecase1",
                DroneCaseTier2 = "dronecase2",
                EEPROM = "eeprom",
                ExperienceUpgrade = "experienceupgrade",
                Floppy = "floppy",
                GeneratorUpgrade = "generatorupgrade",
                GraphicsCardTier1 = "graphicscard1",
                GraphicsCardTier2 = "graphicscard2",
                GraphicsCardTier3 = "graphicscard3",
                HDDTier1 = "hdd1",
                HDDTier2 = "hdd2",
                HDDTier3 = "hdd3",
                HoverBoots = "hoverboots",
                HoverUpgradeTier1 = "hoverupgrade1",
                HoverUpgradeTier2 = "hoverupgrade2",
                InkCartridgeEmpty = "inkcartridgeempty",
                InkCartridge = "inkcartridge",
                InternetCard = "internetcard",
                Interweb = "interweb",
                InventoryControllerUpgrade = "inventorycontrollerupgrade",
                InventoryUpgrade = "inventoryupgrade",
                LeashUpgrade = "leashupgrade",
                LinkedCard = "linkedcard",
                LuaBios = "luabios",
                MFU = "mfu",
                Manual = "manual",
                MicrocontrollerCaseCreative = "microcontrollercasecreative",
                MicrocontrollerCaseTier1 = "microcontrollercase1",
                MicrocontrollerCaseTier2 = "microcontrollercase2",
                Nanomachines = "nanomachines",
                NavigationUpgrade = "navigationupgrade",
                NetworkCard = "lancard",
                NumPad = "numpad",
                OpenOS = "openos",
                PistonUpgrade = "pistonupgrade",
                StickyPistonUpgrade = "stickypistonupgrade",
                Present = "present",
                PrintedCircuitBoard = "printedcircuitboard",
                RAMTier1 = "ram1",
                RAMTier2 = "ram2",
                RAMTier3 = "ram3",
                RAMTier4 = "ram4",
                RAMTier5 = "ram5",
                RAMTier6 = "ram6",
                RawCircuitBoard = "rawcircuitboard",
                RedstoneCardTier1 = "redstonecard1",
                RedstoneCardTier2 = "redstonecard2",
                ServerCreative = "servercreative",
                ServerTier1 = "server1",
                ServerTier2 = "server2",
                ServerTier3 = "server3",
                SignUpgrade = "signupgrade",
                SolarGeneratorUpgrade = "solargeneratorupgrade",
                Tablet = "tablet",
                TabletCaseCreative = "tabletcasecreative",
                TabletCaseTier1 = "tabletcase1",
                TabletCaseTier2 = "tabletcase2",
                TankControllerUpgrade = "tankcontrollerupgrade",
                TankUpgrade = "tankupgrade",
                Terminal = "terminal",
                TerminalServer = "terminalserver",
                TexturePicker = "texturepicker",
                TractorBeamUpgrade = "tractorbeamupgrade",
                TradingUpgrade = "tradingupgrade",
                Transistor = "transistor",
                UpgradeContainerTier1 = "upgradecontainer1",
                UpgradeContainerTier2 = "upgradecontainer2",
                UpgradeContainerTier3 = "upgradecontainer3",
                WirelessNetworkCardTier1 = "wlancard1",
                WirelessNetworkCardTier2 = "wlancard2",
                WorldSensorCard = "worldsensorcard",
                Wrench = "wrench";

        // def DroneCase(tier: Int): String = ItemUtils.caseNameWithTierSuffix("dronecase", tier)
        // def MicrocontrollerCase(tier: Int): String = ItemUtils.caseNameWithTierSuffix("microcontrollercase", tier)
        // def TabletCase(tier: Int): String = ItemUtils.caseNameWithTierSuffix("tabletcase", tier)
    }

    public class DeviceInfo {
        public static final String
                DefaultVendor = "MightyPirates GmbH & Co. KG",
                Scummtech = "Scummtech, Inc.";
    }
}
